# Generated by Django 5.2.7 on 2025-11-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='usuario',
            new_name='user',
        ),
    ]
